services:
  app:
    container_name: app_backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        - PORT=${PORT}
    image: app_emp:${IMAGE_TAG}
    ports:
      - "${PORT}:${PORT}"
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:

