name: Deploy to Production

on:
  push:
    workflows_dispatch: true
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          # Aquí irían los comandos reales de despliegue
        # Puedes usar secretos para las credenciales si es necesario
        # env:
        #   DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

      - name: Post-deployment tasks
        run: |
          echo "Running post-deployment tasks..."