name: Node

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build && find dist/main.js
      - name: Run Lint code
        run: yarn lint
      - name: Run Test
        run: yarn test
